services:
  short-link-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: short-link:1.0
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
    command: ./wait-for-it.sh postgres:5432 --npm start
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_NAME: short_link
      DB_USER: user
      DB_PASSWORD: pass
      REDIS_HOST: redis

  redis:
    image: redis:6.0-alpine
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: kutt
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/short-link/db_data/redis_data
      o: bind
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/short-link/db_data/postgres_data
      o: bind
