services:
  short-link-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: walkerzhuo/short-link:1.0
    container_name: standalone.short-link
    depends_on:
      - postgres
      - redis
    command: ./wait-for-it.sh postgres:5432 -- npm start
    ports:
      - "3000:3000"
    env_file:
      - .example.env # rename this file to .env on production
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis

  redis:
    image: redis:6.0-alpine
    volumes:
      - short_link_redis_data:/data

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: short_link
    ports: 
      - "5432:5432"
    volumes:
      - short_link_postgres_data:/var/lib/postgresql/data

volumes:
  short_link_redis_data:
  short_link_postgres_data:
